/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as CriarConteudoRouteImport } from './routes/criar-conteudo'
import { Route as EntrarRouteImport } from './routes/entrar'
import { Route as EuRouteImport } from './routes/eu'
import { Route as FiliacaoRouteImport } from './routes/filiacao'
import { Route as LiveRouteImport } from './routes/live'
import { Route as NotificacoesRouteImport } from './routes/notificacoes'
import { Route as OficiaisRouteImport } from './routes/oficiais'
import { Route as AuthenticatedCarrinhoRouteImport } from './routes/_authenticated/carrinho'
import { Route as AuthenticatedCheckoutRouteImport } from './routes/_authenticated/checkout'
import { Route as AuthenticatedPainelRouteImport } from './routes/_authenticated/painel'
import { Route as AuthenticatedPedidosRouteImport } from './routes/_authenticated/pedidos'
import { Route as AuthenticatedVenderRouteImport } from './routes/_authenticated/vender'
import { Route as AfiliadoUsernameRouteImport } from './routes/afiliado.$username'
import { Route as CategoriaSlugRouteImport } from './routes/categoria.$slug'
import { Route as LojaSlugRouteImport } from './routes/loja.$slug'
import { Route as ProdutoIdRouteImport } from './routes/produto.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const CriarConteudoRoute = CriarConteudoRouteImport.update({
  id: '/criar-conteudo',
  path: '/criar-conteudo',
  getParentRoute: () => rootRouteImport,
} as any)
const EntrarRoute = EntrarRouteImport.update({
  id: '/entrar',
  path: '/entrar',
  getParentRoute: () => rootRouteImport,
} as any)
const EuRoute = EuRouteImport.update({
  id: '/eu',
  path: '/eu',
  getParentRoute: () => rootRouteImport,
} as any)
const FiliacaoRoute = FiliacaoRouteImport.update({
  id: '/filiacao',
  path: '/filiacao',
  getParentRoute: () => rootRouteImport,
} as any)
const LiveRoute = LiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificacoesRoute = NotificacoesRouteImport.update({
  id: '/notificacoes',
  path: '/notificacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const OficiaisRoute = OficiaisRouteImport.update({
  id: '/oficiais',
  path: '/oficiais',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedCarrinhoRoute = AuthenticatedCarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCheckoutRoute = AuthenticatedCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPainelRoute = AuthenticatedPainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPedidosRoute = AuthenticatedPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVenderRoute = AuthenticatedVenderRouteImport.update({
  id: '/vender',
  path: '/vender',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AfiliadoUsernameRoute = AfiliadoUsernameRouteImport.update({
  id: '/afiliado/$username',
  path: '/afiliado/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const CategoriaSlugRoute = CategoriaSlugRouteImport.update({
  id: '/categoria/$slug',
  path: '/categoria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaSlugRoute = LojaSlugRouteImport.update({
  id: '/loja/$slug',
  path: '/loja/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutoIdRoute = ProdutoIdRouteImport.update({
  id: '/produto/$id',
  path: '/produto/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/conversas': typeof ConversasRoute
  '/criar-conteudo': typeof CriarConteudoRoute
  '/entrar': typeof EntrarRoute
  '/eu': typeof EuRoute
  '/filiacao': typeof FiliacaoRoute
  '/live': typeof LiveRoute
  '/notificacoes': typeof NotificacoesRoute
  '/oficiais': typeof OficiaisRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/vender': typeof AuthenticatedVenderRoute
  '/afiliado/$username': typeof AfiliadoUsernameRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/buscar': typeof BuscarRoute
  '/conversas': typeof ConversasRoute
  '/criar-conteudo': typeof CriarConteudoRoute
  '/entrar': typeof EntrarRoute
  '/eu': typeof EuRoute
  '/filiacao': typeof FiliacaoRoute
  '/live': typeof LiveRoute
  '/notificacoes': typeof NotificacoesRoute
  '/oficiais': typeof OficiaisRoute
  '/carrinho': typeof AuthenticatedCarrinhoRoute
  '/checkout': typeof AuthenticatedCheckoutRoute
  '/painel': typeof AuthenticatedPainelRoute
  '/pedidos': typeof AuthenticatedPedidosRoute
  '/vender': typeof AuthenticatedVenderRoute
  '/afiliado/$username': typeof AfiliadoUsernameRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/buscar': typeof BuscarRoute
  '/conversas': typeof ConversasRoute
  '/criar-conteudo': typeof CriarConteudoRoute
  '/entrar': typeof EntrarRoute
  '/eu': typeof EuRoute
  '/filiacao': typeof FiliacaoRoute
  '/live': typeof LiveRoute
  '/notificacoes': typeof NotificacoesRoute
  '/oficiais': typeof OficiaisRoute
  '/_authenticated/carrinho': typeof AuthenticatedCarrinhoRoute
  '/_authenticated/checkout': typeof AuthenticatedCheckoutRoute
  '/_authenticated/painel': typeof AuthenticatedPainelRoute
  '/_authenticated/pedidos': typeof AuthenticatedPedidosRoute
  '/_authenticated/vender': typeof AuthenticatedVenderRoute
  '/afiliado/$username': typeof AfiliadoUsernameRoute
  '/categoria/$slug': typeof CategoriaSlugRoute
  '/loja/$slug': typeof LojaSlugRoute
  '/produto/$id': typeof ProdutoIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/buscar'
    | '/conversas'
    | '/criar-conteudo'
    | '/entrar'
    | '/eu'
    | '/filiacao'
    | '/live'
    | '/notificacoes'
    | '/oficiais'
    | '/carrinho'
    | '/checkout'
    | '/painel'
    | '/pedidos'
    | '/vender'
    | '/afiliado/$username'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/buscar'
    | '/conversas'
    | '/criar-conteudo'
    | '/entrar'
    | '/eu'
    | '/filiacao'
    | '/live'
    | '/notificacoes'
    | '/oficiais'
    | '/carrinho'
    | '/checkout'
    | '/painel'
    | '/pedidos'
    | '/vender'
    | '/afiliado/$username'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/buscar'
    | '/conversas'
    | '/criar-conteudo'
    | '/entrar'
    | '/eu'
    | '/filiacao'
    | '/live'
    | '/notificacoes'
    | '/oficiais'
    | '/_authenticated/carrinho'
    | '/_authenticated/checkout'
    | '/_authenticated/painel'
    | '/_authenticated/pedidos'
    | '/_authenticated/vender'
    | '/afiliado/$username'
    | '/categoria/$slug'
    | '/loja/$slug'
    | '/produto/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  BuscarRoute: typeof BuscarRoute
  ConversasRoute: typeof ConversasRoute
  CriarConteudoRoute: typeof CriarConteudoRoute
  EntrarRoute: typeof EntrarRoute
  EuRoute: typeof EuRoute
  FiliacaoRoute: typeof FiliacaoRoute
  LiveRoute: typeof LiveRoute
  NotificacoesRoute: typeof NotificacoesRoute
  OficiaisRoute: typeof OficiaisRoute
  AfiliadoUsernameRoute: typeof AfiliadoUsernameRoute
  CategoriaSlugRoute: typeof CategoriaSlugRoute
  LojaSlugRoute: typeof LojaSlugRoute
  ProdutoIdRoute: typeof ProdutoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/criar-conteudo': {
      id: '/criar-conteudo'
      path: '/criar-conteudo'
      fullPath: '/criar-conteudo'
      preLoaderRoute: typeof CriarConteudoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/entrar': {
      id: '/entrar'
      path: '/entrar'
      fullPath: '/entrar'
      preLoaderRoute: typeof EntrarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eu': {
      id: '/eu'
      path: '/eu'
      fullPath: '/eu'
      preLoaderRoute: typeof EuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/filiacao': {
      id: '/filiacao'
      path: '/filiacao'
      fullPath: '/filiacao'
      preLoaderRoute: typeof FiliacaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/live': {
      id: '/live'
      path: '/live'
      fullPath: '/live'
      preLoaderRoute: typeof LiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notificacoes': {
      id: '/notificacoes'
      path: '/notificacoes'
      fullPath: '/notificacoes'
      preLoaderRoute: typeof NotificacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oficiais': {
      id: '/oficiais'
      path: '/oficiais'
      fullPath: '/oficiais'
      preLoaderRoute: typeof OficiaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/carrinho': {
      id: '/_authenticated/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof AuthenticatedCarrinhoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checkout': {
      id: '/_authenticated/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof AuthenticatedCheckoutRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/painel': {
      id: '/_authenticated/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof AuthenticatedPainelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pedidos': {
      id: '/_authenticated/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof AuthenticatedPedidosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vender': {
      id: '/_authenticated/vender'
      path: '/vender'
      fullPath: '/vender'
      preLoaderRoute: typeof AuthenticatedVenderRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/afiliado/$username': {
      id: '/afiliado/$username'
      path: '/afiliado/$username'
      fullPath: '/afiliado/$username'
      preLoaderRoute: typeof AfiliadoUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/categoria/$slug': {
      id: '/categoria/$slug'
      path: '/categoria/$slug'
      fullPath: '/categoria/$slug'
      preLoaderRoute: typeof CategoriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja/$slug': {
      id: '/loja/$slug'
      path: '/loja/$slug'
      fullPath: '/loja/$slug'
      preLoaderRoute: typeof LojaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produto/$id': {
      id: '/produto/$id'
      path: '/produto/$id'
      fullPath: '/produto/$id'
      preLoaderRoute: typeof ProdutoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarrinhoRoute: typeof AuthenticatedCarrinhoRoute
  AuthenticatedCheckoutRoute: typeof AuthenticatedCheckoutRoute
  AuthenticatedPainelRoute: typeof AuthenticatedPainelRoute
  AuthenticatedPedidosRoute: typeof AuthenticatedPedidosRoute
  AuthenticatedVenderRoute: typeof AuthenticatedVenderRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarrinhoRoute: AuthenticatedCarrinhoRoute,
  AuthenticatedCheckoutRoute: AuthenticatedCheckoutRoute,
  AuthenticatedPainelRoute: AuthenticatedPainelRoute,
  AuthenticatedPedidosRoute: AuthenticatedPedidosRoute,
  AuthenticatedVenderRoute: AuthenticatedVenderRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  BuscarRoute: BuscarRoute,
  ConversasRoute: ConversasRoute,
  CriarConteudoRoute: CriarConteudoRoute,
  EntrarRoute: EntrarRoute,
  EuRoute: EuRoute,
  FiliacaoRoute: FiliacaoRoute,
  LiveRoute: LiveRoute,
  NotificacoesRoute: NotificacoesRoute,
  OficiaisRoute: OficiaisRoute,
  AfiliadoUsernameRoute: AfiliadoUsernameRoute,
  CategoriaSlugRoute: CategoriaSlugRoute,
  LojaSlugRoute: LojaSlugRoute,
  ProdutoIdRoute: ProdutoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
